// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: verifier.proto

package settlement

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SettlementRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId       string                 `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	TxHash          string                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Network         string                 `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	AmountPaid      float64                `protobuf:"fixed64,4,opt,name=amount_paid,json=amountPaid,proto3" json:"amount_paid,omitempty"`
	Currency        string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	SenderAddress   string                 `protobuf:"bytes,6,opt,name=sender_address,json=senderAddress,proto3" json:"sender_address,omitempty"`
	ReceiverAddress string                 `protobuf:"bytes,7,opt,name=receiver_address,json=receiverAddress,proto3" json:"receiver_address,omitempty"`
	BlockNumber     int64                  `protobuf:"varint,8,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SettlementRequest) Reset() {
	*x = SettlementRequest{}
	mi := &file_verifier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementRequest) ProtoMessage() {}

func (x *SettlementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verifier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementRequest.ProtoReflect.Descriptor instead.
func (*SettlementRequest) Descriptor() ([]byte, []int) {
	return file_verifier_proto_rawDescGZIP(), []int{0}
}

func (x *SettlementRequest) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *SettlementRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *SettlementRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *SettlementRequest) GetAmountPaid() float64 {
	if x != nil {
		return x.AmountPaid
	}
	return 0
}

func (x *SettlementRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *SettlementRequest) GetSenderAddress() string {
	if x != nil {
		return x.SenderAddress
	}
	return ""
}

func (x *SettlementRequest) GetReceiverAddress() string {
	if x != nil {
		return x.ReceiverAddress
	}
	return ""
}

func (x *SettlementRequest) GetBlockNumber() int64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

type SettlementResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MerchantId      string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	ReceiverAddress string                 `protobuf:"bytes,3,opt,name=receiver_address,json=receiverAddress,proto3" json:"receiver_address,omitempty"`
	SenderAddress   string                 `protobuf:"bytes,4,opt,name=sender_address,json=senderAddress,proto3" json:"sender_address,omitempty"`
	BlockNumber     float64                `protobuf:"fixed64,5,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	Message         string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SettlementResponse) Reset() {
	*x = SettlementResponse{}
	mi := &file_verifier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementResponse) ProtoMessage() {}

func (x *SettlementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_verifier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementResponse.ProtoReflect.Descriptor instead.
func (*SettlementResponse) Descriptor() ([]byte, []int) {
	return file_verifier_proto_rawDescGZIP(), []int{1}
}

func (x *SettlementResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SettlementResponse) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *SettlementResponse) GetReceiverAddress() string {
	if x != nil {
		return x.ReceiverAddress
	}
	return ""
}

func (x *SettlementResponse) GetSenderAddress() string {
	if x != nil {
		return x.SenderAddress
	}
	return ""
}

func (x *SettlementResponse) GetBlockNumber() float64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *SettlementResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_verifier_proto protoreflect.FileDescriptor

const file_verifier_proto_rawDesc = "" +
	"\n" +
	"\x0everifier.proto\x12\n" +
	"settlement\"\x97\x02\n" +
	"\x11SettlementRequest\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\tR\tinvoiceId\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\tR\x06txHash\x12\x18\n" +
	"\anetwork\x18\x03 \x01(\tR\anetwork\x12\x1f\n" +
	"\vamount_paid\x18\x04 \x01(\x01R\n" +
	"amountPaid\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12%\n" +
	"\x0esender_address\x18\x06 \x01(\tR\rsenderAddress\x12)\n" +
	"\x10receiver_address\x18\a \x01(\tR\x0freceiverAddress\x12!\n" +
	"\fblock_number\x18\b \x01(\x03R\vblockNumber\"\xde\x01\n" +
	"\x12SettlementResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12)\n" +
	"\x10receiver_address\x18\x03 \x01(\tR\x0freceiverAddress\x12%\n" +
	"\x0esender_address\x18\x04 \x01(\tR\rsenderAddress\x12!\n" +
	"\fblock_number\x18\x05 \x01(\x01R\vblockNumber\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage2p\n" +
	"\x11SettlementService\x12[\n" +
	"\x1aVerifyAndSettleTransaction\x12\x1d.settlement.SettlementRequest\x1a\x1e.settlement.SettlementResponseB\x1dZ\x1bgo-backend/proto/settlementb\x06proto3"

var (
	file_verifier_proto_rawDescOnce sync.Once
	file_verifier_proto_rawDescData []byte
)

func file_verifier_proto_rawDescGZIP() []byte {
	file_verifier_proto_rawDescOnce.Do(func() {
		file_verifier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_verifier_proto_rawDesc), len(file_verifier_proto_rawDesc)))
	})
	return file_verifier_proto_rawDescData
}

var file_verifier_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_verifier_proto_goTypes = []any{
	(*SettlementRequest)(nil),  // 0: settlement.SettlementRequest
	(*SettlementResponse)(nil), // 1: settlement.SettlementResponse
}
var file_verifier_proto_depIdxs = []int32{
	0, // 0: settlement.SettlementService.VerifyAndSettleTransaction:input_type -> settlement.SettlementRequest
	1, // 1: settlement.SettlementService.VerifyAndSettleTransaction:output_type -> settlement.SettlementResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_verifier_proto_init() }
func file_verifier_proto_init() {
	if File_verifier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_verifier_proto_rawDesc), len(file_verifier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_verifier_proto_goTypes,
		DependencyIndexes: file_verifier_proto_depIdxs,
		MessageInfos:      file_verifier_proto_msgTypes,
	}.Build()
	File_verifier_proto = out.File
	file_verifier_proto_goTypes = nil
	file_verifier_proto_depIdxs = nil
}
